### ISSUE TITLE
Tracking: Alpine 3.14 EOL scheduled for 1st May 2023

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#443]
- [ ] Open a PR and deprecate/EOL alpine 3.14
- [x] Update https://github.com/devcontainers/images/issues/90
- [ ] Update templates if necessary

**Comment by samruddhikhandale** [comment]
Closing as completed.
