### ISSUE TITLE
Tracking: Node 14 EOL scheduled for 30th April 2023 

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#445]
- [x] Open a PR and deprecate/EOL node 14
- [x] Update templates if necessary
- [x] Update https://github.com/devcontainers/images/issues/90

**Comment by samruddhikhandale** [comment]
Closing as completed
