### ISSUE TITLE
Tracking: Ruby 2.7 EOL scheduled for 31st March 2023

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#447]
- [x] Open a PR and deprecate/EOL Ruby 2.7
- [ ] Create a release
- [x] Update templates if necessary
- [x] Update https://github.com/devcontainers/images/issues/90

**Comment by samruddhikhandale** [comment]
Closing as completed 🚀
