### ISSUE TITLE
Tracking: Node 20 release scheduled for 18th April 2023

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#521]
- [ ] Open a PR and support Node 20
- [ ] Create a release
- [ ] Update templates if necessary
- [ ] Update https://github.com/devcontainers/images/issues/90

**Comment by samruddhikhandale** [comment]
Duplicate
