### ISSUE TITLE
Tracking: Ubuntu 18.04 EOSS scheduled for 31st May 2023

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#567]
- [x] Open a PR and deprecate Ubuntu 18.04
- [x] Update https://github.com/devcontainers/images/issues/90
- [x] Update templates if necessary

**Comment by samruddhikhandale** [comment]
Closing as completed 🚀
