### ISSUE TITLE
Tracking: Python 3.7 EOL scheduled for 27th June 2023

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/images#590]
- [x] Check if there's a one final release before deprecating
- [x]  Open a PR and deprecate/EOL Python 3.7
- [x] Update templates if necessary
- [x] Update https://github.com/devcontainers/images/issues/90
